title: Simple Ruby
author: bpohoriletz
email: bohdan.pohorilets@gmail.com
description: >
  I tink my time to give back to the Rails community has come.

github_username: bpohoriletz
google_analytics: UA-108251168-1

# Minima date format
minima:
  date_format: "%b %-d, %Y"
plugins:
- jekyll-feed
# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
