title: Simple Ruby
author: bpohoriletz
email: bohdan.pohorilets@gmail.com
description: >
   <cite>I’m not the best Ruby person around and I’m definitely not the best OO designer,
   but I do have an alternative pattern to suggest.
   </cite>
   <br />
   Sandi Metz
   <br />
   <br />
   <cite>I'm aiming to start a discussion,
   not a religious war. Strong opinions are welcome.
   </cite>
   <br />
   Sandi Metz
url: "https://bpohoriletz.github.io"
baseurl: ""
github_username: bpohoriletz
twitter_username: bpohoriletz
google_analytics: UA-108251168-1
disqus:
  shortname: bpohoriletz

# Minima date format
minima:
  date_format: "%b %-d, %Y"
plugins:
  - jekyll-feed
# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
