# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f7fabe183ea2167a3323bf3a0da05f906b8ba5083915968c51bcf717859e42cfc791b29725014efca81bc216a5a8b1030916aa72ff260e529506a2e5ffa2d80

test:
  secret_key_base: 280446c3e09dbd23b78d1b641f4367765bd2ab03760f27b4936a013c6c5573315a9466c2603963fb4c4f6a18945e2dc89833b356fefadc8e23bfb53392040ce7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
