# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Use SCSS for stylesheets
gem 'activesupport'
gem 'draper'
gem 'sass-rails'
gem 'uuid'

group :development, :test do
  gem 'pry-byebug'
  gem 'rspec-rails'
end
